LOG_DIR = "logs"
DATA_FILE = "jobs.json"
LAST_SCRAPED_FILE = "last_scraped.json"
FORBIDDEN_KEYWORDS = [
    "account",
    "ai",
    "artificial intelligence",
    "bi",
    "brand",
    "business development",
    "business intelligence",
    "deal",
    "director",
    "editor",
    "entry level",
    "executive",
    "field",
    "founder",
    "head",
    "intern",
    "lead",
    "laborer",
    "manager",
    "marketing",
    "operation",
    "principal",
    "product",
    "recruiter",
    "sale",
    "sap",
    "scientist",
    "search",
    "seo",
    "strateg",
    "talent aquisition",
    "technician",
    "technisian",
    "veterinarian",
]
SEARCH_KEYWORDS = [
    "scraping",
    "crawling",
    "data%20aquisition",
    "scraper",
    "crawler",
    "anti-bot",
    "antibot",
]
FORBIDDEN_COMPANIES = [
    "infatica.io",
    "corsearch",
    "mindrift",
    "wayops",
    "duckduckgo",
]
