package remoterocketship

import "time"

type RemoteRockJobList struct {
	Props struct {
		PageProps struct {
			InitialFilters struct {
				SeniorityFilters                []any    `json:"seniorityFilters"`
				LocationFilters                 []string `json:"locationFilters"`
				LocationCityFilters             []any    `json:"locationCityFilters"`
				ShowHybridJobs                  bool     `json:"showHybridJobs"`
				ShowOnsiteJobs                  bool     `json:"showOnsiteJobs"`
				ShowRemoteJobs                  bool     `json:"showRemoteJobs"`
				KeywordFilters                  []any    `json:"keywordFilters"`
				ExcludedKeywordFilters          []any    `json:"excludedKeywordFilters"`
				TechStackFilters                []any    `json:"techStackFilters"`
				RequiredLanguagesFilters        []any    `json:"requiredLanguagesFilters"`
				ExcludeRequiredLanguagesFilters []any    `json:"excludeRequiredLanguagesFilters"`
				JobTitleFilters                 []string `json:"jobTitleFilters"`
				CompanySizeFilters              []any    `json:"companySizeFilters"`
				EmploymentTypeFilters           []any    `json:"employmentTypeFilters"`
				VisaFilter                      any      `json:"visaFilter"`
				MinSalaryFilter                 any      `json:"minSalaryFilter"`
				DegreeRequiredFilter            any      `json:"degreeRequiredFilter"`
				IsOnLinkedInFilter              any      `json:"isOnLinkedInFilter"`
				IndustriesFilters               []any    `json:"industriesFilters"`
				ExcludeIndustriesFilters        []any    `json:"excludeIndustriesFilters"`
				SortType                        string   `json:"sortType"`
				Page                            int      `json:"page"`
			} `json:"initialFilters"`
			InitialJobOpenings []struct {
				ID                                      int       `json:"id"`
				CreatedAt                               time.Time `json:"created_at"`
				DateDeleted                             any       `json:"dateDeleted"`
				RoleTitle                               string    `json:"roleTitle"`
				RequiredLanguages                       []string  `json:"requiredLanguages"`
				DescriptionLanguage                     string    `json:"descriptionLanguage"`
				ValidUntilDate                          any       `json:"validUntilDate"`
				JobDescriptionSummary                   string    `json:"jobDescriptionSummary"`
				TwoLineJobDescriptionSummary            string    `json:"twoLineJobDescriptionSummary"`
				EducationRequirementsCredentialCategory string    `json:"educationRequirementsCredentialCategory"`
				URL                                     string    `json:"url"`
				IsOnLinkedIn                            bool      `json:"isOnLinkedIn"`
				IsEntryLevel                            bool      `json:"isEntryLevel"`
				IsJunior                                bool      `json:"isJunior"`
				IsMidLevel                              bool      `json:"isMidLevel"`
				IsSenior                                bool      `json:"isSenior"`
				IsLead                                  bool      `json:"isLead"`
				SalaryRange                             any       `json:"salaryRange"`
				TechStack                               []string  `json:"techStack"`
				Slug                                    string    `json:"slug"`
				IsPromoted                              bool      `json:"isPromoted"`
				EmploymentType                          string    `json:"employmentType"`
				Location                                string    `json:"location"`
				LocationUSStates                        any       `json:"locationUSStates"`
				LocationCity                            any       `json:"locationCity"`
				LocationType                            string    `json:"locationType"`
				CategorizedJobTitle                     string    `json:"categorizedJobTitle"`
				CategorizedJobFunction                  string    `json:"categorizedJobFunction"`
				RoleTitleBrazil                         any       `json:"roleTitleBrazil"`
				RoleDescriptionBrazil                   any       `json:"roleDescriptionBrazil"`
				RoleRequirementsBrazil                  any       `json:"roleRequirementsBrazil"`
				BenefitsBrazil                          any       `json:"benefitsBrazil"`
				SlugBrazil                              any       `json:"slugBrazil"`
				JobDescriptionSummaryBrazil             any       `json:"jobDescriptionSummaryBrazil"`
				TwoLineJobDescriptionSummaryBrazil      any       `json:"twoLineJobDescriptionSummaryBrazil"`
				RoleTitleFrance                         any       `json:"roleTitleFrance"`
				RoleDescriptionFrance                   any       `json:"roleDescriptionFrance"`
				RoleRequirementsFrance                  any       `json:"roleRequirementsFrance"`
				BenefitsFrance                          any       `json:"benefitsFrance"`
				SlugFrance                              any       `json:"slugFrance"`
				JobDescriptionSummaryFrance             any       `json:"jobDescriptionSummaryFrance"`
				TwoLineJobDescriptionSummaryFrance      any       `json:"twoLineJobDescriptionSummaryFrance"`
				RoleTitleGermany                        any       `json:"roleTitleGermany"`
				RoleDescriptionGermany                  any       `json:"roleDescriptionGermany"`
				RoleRequirementsGermany                 any       `json:"roleRequirementsGermany"`
				BenefitsGermany                         any       `json:"benefitsGermany"`
				SlugGermany                             any       `json:"slugGermany"`
				JobDescriptionSummaryGermany            any       `json:"jobDescriptionSummaryGermany"`
				TwoLineJobDescriptionSummaryGermany     any       `json:"twoLineJobDescriptionSummaryGermany"`
				RoleDescription                         any       `json:"roleDescription"`
				RoleRequirements                        any       `json:"roleRequirements"`
				Benefits                                any       `json:"benefits"`
				Company                                 struct {
					ID                          int      `json:"id"`
					Name                        string   `json:"name"`
					Slug                        string   `json:"slug"`
					ProfilePicURL               string   `json:"profilePicURL"`
					HomePageURL                 string   `json:"homePageURL"`
					ChatGPTIndustries           []string `json:"chatGPTIndustries"`
					LinkedInURL                 string   `json:"linkedInURL"`
					EmployeeRange               string   `json:"employeeRange"`
					FundingData                 []any    `json:"fundingData"`
					SponsorsH1B                 bool     `json:"sponsorsH1B"`
					SponsorsUKSkilledWorkerVisa bool     `json:"sponsorsUKSkilledWorkerVisa"`
					IndustrySpecialities        []string `json:"industrySpecialities"`
				} `json:"company"`
			} `json:"initialJobOpenings"`
			InitialTotalJobCount     int `json:"initialTotalJobCount"`
			InitialWeeklyNewCount    int `json:"initialWeeklyNewCount"`
			InitialPercentOnLinkedIn int `json:"initialPercentOnLinkedIn"`
		} `json:"pageProps"`
		NSsp bool `json:"__N_SSP"`
	} `json:"props"`
	Page  string `json:"page"`
	Query struct {
		Page      string `json:"page"`
		Sort      string `json:"sort"`
		JobTitle  string `json:"jobTitle"`
		Locations string `json:"locations"`
	} `json:"query"`
	BuildID               string `json:"buildId"`
	IsFallback            bool   `json:"isFallback"`
	IsExperimentalCompile bool   `json:"isExperimentalCompile"`
	DynamicIds            []int  `json:"dynamicIds"`
	Gssp                  bool   `json:"gssp"`
	ScriptLoader          []any  `json:"scriptLoader"`
}

type RemoteRockJob struct {
	Props struct {
		PageProps struct {
			JobOpening struct {
				ID                                       int       `json:"id"`
				CreatedAt                                time.Time `json:"created_at"`
				ValidUntilDate                           any       `json:"validUntilDate"`
				DateDeleted                              any       `json:"dateDeleted"`
				RequiredLanguages                        []string  `json:"requiredLanguages"`
				DescriptionLanguage                      string    `json:"descriptionLanguage"`
				RoleTitle                                string    `json:"roleTitle"`
				IsOnLinkedIn                             bool      `json:"isOnLinkedIn"`
				RoleDescription                          string    `json:"roleDescription"`
				RoleRequirements                         string    `json:"roleRequirements"`
				Benefits                                 string    `json:"benefits"`
				JobDescriptionSummary                    string    `json:"jobDescriptionSummary"`
				TwoLineJobDescriptionSummary             string    `json:"twoLineJobDescriptionSummary"`
				EducationRequirementsCredentialCategory  any       `json:"educationRequirementsCredentialCategory"`
				ExperienceInPlaceOfEducation             bool      `json:"experienceInPlaceOfEducation"`
				ExperienceRequirementsMonthsOfExperience int       `json:"experienceRequirementsMonthsOfExperience"`
				RoleTitleBrazil                          any       `json:"roleTitleBrazil"`
				RoleDescriptionBrazil                    any       `json:"roleDescriptionBrazil"`
				RoleRequirementsBrazil                   any       `json:"roleRequirementsBrazil"`
				BenefitsBrazil                           any       `json:"benefitsBrazil"`
				SlugBrazil                               any       `json:"slugBrazil"`
				JobDescriptionSummaryBrazil              any       `json:"jobDescriptionSummaryBrazil"`
				TwoLineJobDescriptionSummaryBrazil       any       `json:"twoLineJobDescriptionSummaryBrazil"`
				RoleTitleFrance                          any       `json:"roleTitleFrance"`
				RoleDescriptionFrance                    any       `json:"roleDescriptionFrance"`
				RoleRequirementsFrance                   any       `json:"roleRequirementsFrance"`
				BenefitsFrance                           any       `json:"benefitsFrance"`
				SlugFrance                               any       `json:"slugFrance"`
				JobDescriptionSummaryFrance              any       `json:"jobDescriptionSummaryFrance"`
				TwoLineJobDescriptionSummaryFrance       any       `json:"twoLineJobDescriptionSummaryFrance"`
				RoleTitleGermany                         any       `json:"roleTitleGermany"`
				RoleDescriptionGermany                   any       `json:"roleDescriptionGermany"`
				RoleRequirementsGermany                  any       `json:"roleRequirementsGermany"`
				BenefitsGermany                          any       `json:"benefitsGermany"`
				SlugGermany                              any       `json:"slugGermany"`
				JobDescriptionSummaryGermany             any       `json:"jobDescriptionSummaryGermany"`
				TwoLineJobDescriptionSummaryGermany      any       `json:"twoLineJobDescriptionSummaryGermany"`
				URL                                      string    `json:"url"`
				IsEntryLevel                             bool      `json:"isEntryLevel"`
				IsJunior                                 bool      `json:"isJunior"`
				IsMidLevel                               bool      `json:"isMidLevel"`
				IsSenior                                 bool      `json:"isSenior"`
				IsLead                                   bool      `json:"isLead"`
				SalaryRange                              any       `json:"salaryRange"`
				TechStack                                []string  `json:"techStack"`
				Slug                                     string    `json:"slug"`
				IsPromoted                               bool      `json:"isPromoted"`
				EmploymentType                           string    `json:"employmentType"`
				Location                                 string    `json:"location"`
				LocationType                             string    `json:"locationType"`
				LocationCity                             any       `json:"locationCity"`
				LocationUSStates                         any       `json:"locationUSStates"`
				CategorizedJobTitle                      string    `json:"categorizedJobTitle"`
				CategorizedJobFunction                   string    `json:"categorizedJobFunction"`
				Company                                  struct {
					ID                          int      `json:"id"`
					Name                        string   `json:"name"`
					Slug                        string   `json:"slug"`
					Tagline                     string   `json:"tagline"`
					FoundedYear                 any      `json:"foundedYear"`
					FundingData                 []any    `json:"fundingData"`
					HomePageURL                 string   `json:"homePageURL"`
					LinkedInURL                 string   `json:"linkedInURL"`
					SponsorsH1B                 bool     `json:"sponsorsH1B"`
					EmployeeRange               string   `json:"employeeRange"`
					ProfilePicURL               string   `json:"profilePicURL"`
					TaglineBrazil               string   `json:"taglineBrazil"`
					TaglineFrance               string   `json:"taglineFrance"`
					TaglineGermany              string   `json:"taglineGermany"`
					ChatGPTIndustries           any      `json:"chatGPTIndustries"`
					ChatGPTDescription          any      `json:"chatGPTDescription"`
					LinkedInDescription         string   `json:"linkedInDescription"`
					IndustrySpecialities        []string `json:"industrySpecialities"`
					ChatGPTDescriptionBrazil    string   `json:"chatGPTDescriptionBrazil"`
					ChatGPTDescriptionFrance    any      `json:"chatGPTDescriptionFrance"`
					ChatGPTDescriptionGermany   any      `json:"chatGPTDescriptionGermany"`
					LinkedInDescriptionBrazil   string   `json:"linkedInDescriptionBrazil"`
					LinkedInDescriptionFrance   string   `json:"linkedInDescriptionFrance"`
					IndustrySpecialitiesBrazil  []string `json:"industrySpecialitiesBrazil"`
					IndustrySpecialitiesFrance  []string `json:"industrySpecialitiesFrance"`
					LinkedInDescriptionGermany  string   `json:"linkedInDescriptionGermany"`
					IndustrySpecialitiesGermany []string `json:"industrySpecialitiesGermany"`
					SponsorsUKSkilledWorkerVisa bool     `json:"sponsorsUKSkilledWorkerVisa"`
				} `json:"company"`
			} `json:"jobOpening"`
			RelatedJobs []struct {
				ID                                      int       `json:"id"`
				CreatedAt                               time.Time `json:"created_at"`
				RequiredLanguages                       []string  `json:"requiredLanguages"`
				DescriptionLanguage                     string    `json:"descriptionLanguage"`
				RoleTitle                               string    `json:"roleTitle"`
				JobDescriptionSummary                   string    `json:"jobDescriptionSummary"`
				TwoLineJobDescriptionSummary            string    `json:"twoLineJobDescriptionSummary"`
				EducationRequirementsCredentialCategory any       `json:"educationRequirementsCredentialCategory"`
				RoleTitleBrazil                         any       `json:"roleTitleBrazil"`
				RoleDescriptionBrazil                   any       `json:"roleDescriptionBrazil"`
				RoleRequirementsBrazil                  any       `json:"roleRequirementsBrazil"`
				BenefitsBrazil                          any       `json:"benefitsBrazil"`
				SlugBrazil                              any       `json:"slugBrazil"`
				JobDescriptionSummaryBrazil             any       `json:"jobDescriptionSummaryBrazil"`
				TwoLineJobDescriptionSummaryBrazil      any       `json:"twoLineJobDescriptionSummaryBrazil"`
				RoleTitleFrance                         any       `json:"roleTitleFrance"`
				RoleDescriptionFrance                   any       `json:"roleDescriptionFrance"`
				RoleRequirementsFrance                  any       `json:"roleRequirementsFrance"`
				BenefitsFrance                          any       `json:"benefitsFrance"`
				SlugFrance                              any       `json:"slugFrance"`
				JobDescriptionSummaryFrance             any       `json:"jobDescriptionSummaryFrance"`
				TwoLineJobDescriptionSummaryFrance      any       `json:"twoLineJobDescriptionSummaryFrance"`
				RoleTitleGermany                        any       `json:"roleTitleGermany"`
				RoleDescriptionGermany                  any       `json:"roleDescriptionGermany"`
				RoleRequirementsGermany                 any       `json:"roleRequirementsGermany"`
				BenefitsGermany                         any       `json:"benefitsGermany"`
				SlugGermany                             any       `json:"slugGermany"`
				JobDescriptionSummaryGermany            any       `json:"jobDescriptionSummaryGermany"`
				TwoLineJobDescriptionSummaryGermany     any       `json:"twoLineJobDescriptionSummaryGermany"`
				URL                                     string    `json:"url"`
				IsEntryLevel                            bool      `json:"isEntryLevel"`
				IsJunior                                bool      `json:"isJunior"`
				IsMidLevel                              bool      `json:"isMidLevel"`
				IsSenior                                bool      `json:"isSenior"`
				IsLead                                  bool      `json:"isLead"`
				SalaryRange                             struct {
					Max                     int    `json:"max"`
					Min                     int    `json:"min"`
					SalaryType              string `json:"salaryType"`
					CurrencyCode            string `json:"currencyCode"`
					CurrencySymbol          string `json:"currencySymbol"`
					MaxSalaryAsUSD          int    `json:"maxSalaryAsUSD"`
					MinSalaryAsUSD          int    `json:"minSalaryAsUSD"`
					SalaryHumanReadableText string `json:"salaryHumanReadableText"`
				} `json:"salaryRange"`
				TechStack              []string `json:"techStack"`
				Slug                   string   `json:"slug"`
				IsPromoted             bool     `json:"isPromoted"`
				EmploymentType         string   `json:"employmentType"`
				Location               string   `json:"location"`
				LocationType           string   `json:"locationType"`
				LocationCity           any      `json:"locationCity"`
				CategorizedJobTitle    string   `json:"categorizedJobTitle"`
				CategorizedJobFunction string   `json:"categorizedJobFunction"`
				Company                struct {
					ID                          int      `json:"id"`
					Name                        string   `json:"name"`
					Slug                        string   `json:"slug"`
					FundingData                 []any    `json:"fundingData"`
					HomePageURL                 string   `json:"homePageURL"`
					LinkedInURL                 string   `json:"linkedInURL"`
					SponsorsH1B                 bool     `json:"sponsorsH1B"`
					EmployeeRange               string   `json:"employeeRange"`
					ProfilePicURL               string   `json:"profilePicURL"`
					ChatGPTIndustries           []string `json:"chatGPTIndustries"`
					SponsorsUKSkilledWorkerVisa bool     `json:"sponsorsUKSkilledWorkerVisa"`
				} `json:"company"`
			} `json:"relatedJobs"`
			Language string `json:"language"`
		} `json:"pageProps"`
		NSsp bool `json:"__N_SSP"`
	} `json:"props"`
	Page  string `json:"page"`
	Query struct {
		CompanySlug string `json:"companySlug"`
		JobSlug     string `json:"jobSlug"`
	} `json:"query"`
	BuildID               string `json:"buildId"`
	IsFallback            bool   `json:"isFallback"`
	IsExperimentalCompile bool   `json:"isExperimentalCompile"`
	DynamicIds            []int  `json:"dynamicIds"`
	Gssp                  bool   `json:"gssp"`
	ScriptLoader          []any  `json:"scriptLoader"`
}
